- name: Destroy Bosh Director VMs
  shell: |
    bosh delete-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -v director_name={{ bosh.director_name }} \
    -v internal_cidr={{ bosh.internal_cidr }} \
    -v internal_gw={{ bosh.internal_gw }} \
    -v internal_ip={{ bosh.internal_ip }} \
    -v network_name="{{ bosh.vm_network }}" \
    -v vcenter_dc={{ vcenter.datacenter }} \
    -v vcenter_ds={{ vcenter.datastore }} \
    -v vcenter_ip={{ vcenter.ip_addr }} \
    -v vcenter_user={{ vcenter.username }} \
    -v vcenter_password="{{ vcenter.password }}" \
    -v vcenter_templates={{ bosh.director_name }}-templates \
    -v vcenter_vms={{ bosh.director_name }}-vms \
    -v vcenter_disks={{ bosh.director_name }}-disks \
    -v vcenter_cluster={{ vcenter.cluster }}
  register: delete_cf_cli
  args:
    chdir: "{{ base_path }}/{{ bosh.director_name }}"
- debug: msg={{ delete_cf_cli }}

